version: '3'
services:
  db:
    container_name: db
    image: library/postgres:12-alpine
    env_file:
      - database.env
    ports:
      - 5433:5432
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: