server:
  port: 8080

spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: ${LOGGING_SPRING:ERROR}
    by.netcracker: ${LOGGING_PACKAGE:ERROR}