server:
  port: 8080

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:8000/enterprise-db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    platform: POSTGRESQL
    driver-class-name: org.postgresql.Driver
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework: ${LOGGING_SPRING:ERROR}
    by.netcracker: ${LOGGING_PACKAGE:ERROR}